name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restaurar pacotes
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --configuration Release

      - name: Executar testes
        run: dotnet test --logger "trx;LogFileName=testresults.trx"

      - name: Fazer upload dos resultados dos testes
        uses: actions/upload-artifact@v2
        with:
          name: Resultados dos Testes
          path: "**/testresults.trx"
