name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore packages
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Execute tests
      run: dotnet test --logger "trx;LogFileName=testresults.trx"

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        testResultsFile: "**/testresults.trx"

    - name: Publish package
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          ./publish
          **/testresults.trx
