name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx"

      - name: Publish package
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ./publish
