name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restaurar pacotes
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --configuration Release

      - name: Executar testes
        run: dotnet test --logger "trx;LogFileName=testresults.trx"

      - name: Gerar relatório de teste
        run: dotnet test --logger "trx;LogFileName=testresults.trx" --results-directory ./TestResults

      - name: Empacotar software
        run: dotnet publish --configuration Release --output ./PublishOutput

      - name: Fazer upload do relatório de teste
        uses: actions/upload-artifact@v2
        with:
          name: Relatório de Teste
          path: ./TestResults

      - name: Fazer upload do pacote
        uses: actions/upload-artifact@v2
        with:
          name: Pacote
          path: ./PublishOutput
